Repository ud-cis-discord/Sage, pull requests merged in 2022-02, with the labels that each got.

#243 Slashification of Staff + reminder commands
  src/commands/configuration/togglepii.ts
  src/commands/reminders/cancelreminder.ts
  src/commands/reminders/remind.ts
  src/commands/reminders/viewreminders.ts
  src/commands/staff/addassignment.ts
  src/commands/staff/google.ts
  src/commands/staff/lookup.ts
  src/commands/staff/mute.ts
  src/commands/staff/resetlevel.ts
  src/commands/staff/roleinfo.ts
  src/commands/staff/sudoreply.ts
  src/commands/staff/warn.ts
  src/commands/staff/whois.ts
  src/lib/permissions.ts
  src/lib/types/Command.ts
  src/lib/utils.ts
  src/pieces/commandManager.ts
  src/pieces/remind.ts
Labels: enhancement

#245 feat: add LaTeX rendering command
  src/commands/fun/latex.ts
Labels: enhancement

#244 Ren slashification
  config.example.ts
  src/commands/admin/activity.ts
  src/commands/admin/addcourse.ts
  src/commands/admin/announce.ts
  src/commands/admin/disable.ts
  src/commands/admin/edit.ts
  src/commands/admin/enable.ts
  src/commands/admin/issue.ts
  src/commands/admin/prune.ts
  src/commands/admin/removecourse.ts
  src/commands/admin/resetlevels.ts
  src/commands/admin/restart.ts
  src/commands/admin/setassign.ts
  src/commands/admin/showcommands.ts
  src/commands/admin/shutdown.ts
  src/commands/admin/status.ts
  src/commands/admin/sudo.ts
  src/commands/configuration/enroll.ts
  src/commands/staff/warn.ts
  src/lib/permissions.ts
  src/lib/utils.ts
  src/pieces/commandManager.ts
Labels: enhancement, IS Requirement

#251 autodocs dont use antiquated command usage
  autodoc/writecommands.ts
Labels: bug, documentation

#261 Lookup hotfix
  src/commands/staff/lookup.ts
  src/commands/staff/whois.ts
Labels: bug, tweak
